import { getServerSession } from "next-auth";
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "The Real Vkontakte",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang="ru">

      <body>

        <header className="flex justify-between">
          <div>LOGO</div>

          <nav>
            {
              session ?
                (<Link href='/login'>Выход</Link>) :
                (<Link href='/login'>Вход</Link>)
            }
          </nav>
        </header>


        {children}
      </body>
    </html >
  );
}
