import { getServerSession } from "next-auth";
import "./globals.css";
import Link from "next/link";
import authConfig from "@/authConfig";
import TheHeader from "@/components/blocks/TheHeader";

export const metadata = {
  title: "The Real Vkontakte",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authConfig)
  return (
    <html lang="ru">

      <body>

        <TheHeader session={session} />

        <main className="max-w-[1200px] mx-auto py-10">
          {children}
        </main>
      </body>
    </html >
  );
}
